apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-uam-adapter-pubsub
scopes:
  - uam-adapter
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: {{ .Values.envValues.KAFKA_BROKER }}
    - name: consumerGroup
      value: {{ .Values.envValues.KAFKA_CONSUMER_GROUP }}
    - name: clientID
      value: {{ .Values.envValues.KAFKA_CLIENT_ID }}
    - name: authType
      value: {{ .Values.envValues.KAFKA_AUTH_TYPE }}
    - name: maxMessageBytes
      value: {{ .Values.envValues.KAFKA_MAX_MSG_BYTES }}
    - name: consumerRetryInterval
      value: {{ .Values.envValues.KAFKA_CONSUMER_RETRY_INTERVAL }}
    - name: disableTls
      value: {{ .Values.envValues.KAFKA_DISABLE_TLS }}
    - name: authRequired
      value: {{ .Values.envValues.KAFKA_AUTH_REQUIRED }}
    - name: retryInterval
      value: {{ .Values.envValues.KAFKA_RETRY_INTERVAL }}
    - name: maxRetryCount
      value: {{ .Values.envValues.KAFKA_MAX_RETRY_COUNT }}
    - name: saslMechanism
      value: {{ .Values.envValues.KAFKA_SASL_MECHANISM }}
    - name: saslUsername
      value: {{ .Values.envValues.KAFKA_SASL_USERNAME }}
 #   - name: saslPassword
 #     secretKeyRef:
 #       name: uam-adapter-cloud-secret
  #      key: saslPassword
  #  - name: caCert
  #    secretKeyRef:
  #      name: uam-adapter-cloud-secret
  #      key: caCert
    - name: sasl
      value: {{ .Values.envValues.KAFKA_SASL }}
  #  - name: tls
  #    value: {{ .Values.envValues.KAFKA_TLS }}