apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: maintain        
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: {{ .Values.envValues.DEFAULT_MAINTAIN_URL }}