apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eprice-search
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: urL
      value : {{ .Values.envValues.EPRICE_SEARCH_URL }}