{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "prarambh-uam-adapter-helm.fullname" . }}
  labels:
    {{- include "prarambh-uam-adapter-helm.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    
spec:
  defaultBackend:
    service:
      name: {{ include "prarambh-uam-adapter-helm.fullname" . }}
      port:
        number: {{.Values.ingress.backendPortNumber}}
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "prarambh-uam-adapter-helm.fullname" . }}
                port:
                  number: {{ .Values.ingress.backendPortNumber }}
{{- end }}