{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-service-account
  labels:
    {{- include "prarambh-uam-adapter-helm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-4" #This decides about the precedence of loading the hook with the lowest weight first (negative to positive)
    iam.gke.io/gcp-service-account: { { .Values.serviceAccount.name } }

