apiVersion: secret-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: uam-adapter-secret-provider
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  provider: gcp
  secretObjects:
  - secretName: uam-adapter-cloud-secret
    type: Opaque
    data:
      # - objectName: saslPassword.data
      #key: saslPassword
      #- objectName: caCert.data
      #key: caCert
      - objectName: dbPassword.data
        key: dbPassword

  parameters:
    secrets: |
      {{- range $key, $val := .Values.global.uamcloudsecret }}
      - resourceName: {{ $val.resourceName | toYaml }}
        fileName: {{ $val.fileName | toYaml }}
        {{- end }}
    
        
